[project]
name = "rerun-ros"
authors = ["rerun.io <opensource@rerun.io>"]
channels = ["robostack-jazzy", "conda-forge"]
description = "rerun-ros"
homepage = "https://rerun.io"
license = "MIT OR Apache-2.0"

platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64", "win-64"]
readme = "README.md"
repository = "https://github.com/rerun-io/rerun-ros"
version = "0.1.0"

[tasks]
install-cargo-ament-build = "cargo install --git https://github.com/ros2-rust/cargo-ament-build"
build = { cmd = "colcon build", depends-on = ["install-cargo-ament-build"] }
lint-typos = "typos"

[activation]
env = { ROS_DISTRO = "jazzy" }
scripts = ["install/setup.bash", "install/local_setup.bash"]

[dependencies]
clangdev = "19.1.7.*"
ros-jazzy-rcl = ">=9.2.6,<10"
ros-jazzy-builtin-interfaces = ">=2.0.2,<3"
ros-jazzy-rcl-interfaces = ">=2.0.2,<3"
ros-jazzy-rosgraph-msgs = ">=2.0.2,<3"
ros-jazzy-rosidl-default-generators = ">=1.6.0,<2"
ros-jazzy-ros2cli = ">=0.32.4,<0.33"
ros-jazzy-ros2run = ">=0.32.4,<0.33"
ros-jazzy-ros2cli-common-extensions = ">=0.3.0,<0.4"
ros-jazzy-ros-core = ">=0.11.0,<0.12"
ros-jazzy-geometry-msgs = ">=5.3.6,<6"
ros-jazzy-rosidl-runtime-c = ">=4.6.5,<5"
ros-jazzy-common-interfaces = ">=5.3.6,<6"
typos = ">=1.16.20"

[build-dependencies]
colcon-common-extensions = ">=0.3.0,<0.4"

[pypi-dependencies]
colcon-cargo = { git = "https://github.com/colcon/colcon-cargo.git" }
colcon-ros-cargo = { git = "https://github.com/colcon/colcon-ros-cargo.git" }

[target.linux-64.dependencies]
sysroot_linux-64 = ">=2.17,<3" # rustc 1.64+ requires glibc 2.17+, see https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html

[target.linux-aarch64.dependencies]
sysroot_linux-aarch64 = ">=2.17,<3" # rustc 1.64+ requires glibc 2.17+, see https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html
