[api]
enabled = true
address = "127.0.0.1:9888"

[topics.status]
topic = "status"
ros_type = "std_msgs/msg/String"
archetype = "TextDocument"

[streams.viewer]
inputs = ["status"]
url = "rerun+http://127.0.0.1:9876/proxy"

[db]
inputs = ["status"]
data_dir = "/path/to/data"
